server:
  error:
    include-message: always
  context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 10MB
---
spring:
  profiles: prod
  datasource:
    username: pollarbear
    url: jdbc:postgresql://localhost/pollarbear
  jpa:
    hibernate:
      ddl-auto: update
