server:
  error:
    include-message: always
---
spring:
  profiles: prod
  datasource:
    username: pollarbear
    url: jdbc:postgresql://localhost/pollarbear
  jpa:
    hibernate:
      ddl-auto: update
